title: Machine Learning Engineer
description: Independent AI Consultant with 7+ years of experience
url: "https://yourusername.github.io"
baseurl: "/blog"

# GitHub Pages settings
source: docs
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Theme settings
theme: minima

# Markdown settings
markdown: kramdown
highlighter: rouge

# Collections configuration
collections:
  notes:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
